/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DrugsIndexImport } from './routes/drugs/index'
import { Route as ConditionsIndexImport } from './routes/conditions/index'
import { Route as CalcIndexImport } from './routes/calc/index'
import { Route as DrugsKeyImport } from './routes/drugs/$key'
import { Route as ConditionsKeyImport } from './routes/conditions/$key'
import { Route as CalcPeakFlowRateImport } from './routes/calc/peak-flow-rate'
import { Route as CalcOxygenGradientImport } from './routes/calc/oxygen-gradient'
import { Route as CalcMetabolicAlkalosisImport } from './routes/calc/metabolic-alkalosis'
import { Route as CalcMetabolicAcidosisImport } from './routes/calc/metabolic-acidosis'
import { Route as CalcGlasgowComaScaleImport } from './routes/calc/glasgow-coma-scale'
import { Route as CalcCorrectedSodiumImport } from './routes/calc/corrected-sodium'
import { Route as CalcChronicRespiratoryAlkalosisImport } from './routes/calc/chronic-respiratory-alkalosis'
import { Route as CalcChronicRespiratoryAcidosisImport } from './routes/calc/chronic-respiratory-acidosis'
import { Route as CalcAnionGapImport } from './routes/calc/anion-gap'
import { Route as CalcAcuteRespiratoryAlkalosisImport } from './routes/calc/acute-respiratory-alkalosis'
import { Route as CalcAcuteRespiratoryAcidosisImport } from './routes/calc/acute-respiratory-acidosis'

// Create Virtual Routes

const SearchLazyImport = createFileRoute('/search')()

// Create/Update Routes

const SearchLazyRoute = SearchLazyImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DrugsIndexRoute = DrugsIndexImport.update({
  id: '/drugs/',
  path: '/drugs/',
  getParentRoute: () => rootRoute,
} as any)

const ConditionsIndexRoute = ConditionsIndexImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRoute,
} as any)

const CalcIndexRoute = CalcIndexImport.update({
  id: '/calc/',
  path: '/calc/',
  getParentRoute: () => rootRoute,
} as any)

const DrugsKeyRoute = DrugsKeyImport.update({
  id: '/drugs/$key',
  path: '/drugs/$key',
  getParentRoute: () => rootRoute,
} as any)

const ConditionsKeyRoute = ConditionsKeyImport.update({
  id: '/conditions/$key',
  path: '/conditions/$key',
  getParentRoute: () => rootRoute,
} as any)

const CalcPeakFlowRateRoute = CalcPeakFlowRateImport.update({
  id: '/calc/peak-flow-rate',
  path: '/calc/peak-flow-rate',
  getParentRoute: () => rootRoute,
} as any)

const CalcOxygenGradientRoute = CalcOxygenGradientImport.update({
  id: '/calc/oxygen-gradient',
  path: '/calc/oxygen-gradient',
  getParentRoute: () => rootRoute,
} as any)

const CalcMetabolicAlkalosisRoute = CalcMetabolicAlkalosisImport.update({
  id: '/calc/metabolic-alkalosis',
  path: '/calc/metabolic-alkalosis',
  getParentRoute: () => rootRoute,
} as any)

const CalcMetabolicAcidosisRoute = CalcMetabolicAcidosisImport.update({
  id: '/calc/metabolic-acidosis',
  path: '/calc/metabolic-acidosis',
  getParentRoute: () => rootRoute,
} as any)

const CalcGlasgowComaScaleRoute = CalcGlasgowComaScaleImport.update({
  id: '/calc/glasgow-coma-scale',
  path: '/calc/glasgow-coma-scale',
  getParentRoute: () => rootRoute,
} as any)

const CalcCorrectedSodiumRoute = CalcCorrectedSodiumImport.update({
  id: '/calc/corrected-sodium',
  path: '/calc/corrected-sodium',
  getParentRoute: () => rootRoute,
} as any)

const CalcChronicRespiratoryAlkalosisRoute =
  CalcChronicRespiratoryAlkalosisImport.update({
    id: '/calc/chronic-respiratory-alkalosis',
    path: '/calc/chronic-respiratory-alkalosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcChronicRespiratoryAcidosisRoute =
  CalcChronicRespiratoryAcidosisImport.update({
    id: '/calc/chronic-respiratory-acidosis',
    path: '/calc/chronic-respiratory-acidosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcAnionGapRoute = CalcAnionGapImport.update({
  id: '/calc/anion-gap',
  path: '/calc/anion-gap',
  getParentRoute: () => rootRoute,
} as any)

const CalcAcuteRespiratoryAlkalosisRoute =
  CalcAcuteRespiratoryAlkalosisImport.update({
    id: '/calc/acute-respiratory-alkalosis',
    path: '/calc/acute-respiratory-alkalosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcAcuteRespiratoryAcidosisRoute =
  CalcAcuteRespiratoryAcidosisImport.update({
    id: '/calc/acute-respiratory-acidosis',
    path: '/calc/acute-respiratory-acidosis',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/calc/acute-respiratory-acidosis': {
      id: '/calc/acute-respiratory-acidosis'
      path: '/calc/acute-respiratory-acidosis'
      fullPath: '/calc/acute-respiratory-acidosis'
      preLoaderRoute: typeof CalcAcuteRespiratoryAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/acute-respiratory-alkalosis': {
      id: '/calc/acute-respiratory-alkalosis'
      path: '/calc/acute-respiratory-alkalosis'
      fullPath: '/calc/acute-respiratory-alkalosis'
      preLoaderRoute: typeof CalcAcuteRespiratoryAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/anion-gap': {
      id: '/calc/anion-gap'
      path: '/calc/anion-gap'
      fullPath: '/calc/anion-gap'
      preLoaderRoute: typeof CalcAnionGapImport
      parentRoute: typeof rootRoute
    }
    '/calc/chronic-respiratory-acidosis': {
      id: '/calc/chronic-respiratory-acidosis'
      path: '/calc/chronic-respiratory-acidosis'
      fullPath: '/calc/chronic-respiratory-acidosis'
      preLoaderRoute: typeof CalcChronicRespiratoryAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/chronic-respiratory-alkalosis': {
      id: '/calc/chronic-respiratory-alkalosis'
      path: '/calc/chronic-respiratory-alkalosis'
      fullPath: '/calc/chronic-respiratory-alkalosis'
      preLoaderRoute: typeof CalcChronicRespiratoryAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/corrected-sodium': {
      id: '/calc/corrected-sodium'
      path: '/calc/corrected-sodium'
      fullPath: '/calc/corrected-sodium'
      preLoaderRoute: typeof CalcCorrectedSodiumImport
      parentRoute: typeof rootRoute
    }
    '/calc/glasgow-coma-scale': {
      id: '/calc/glasgow-coma-scale'
      path: '/calc/glasgow-coma-scale'
      fullPath: '/calc/glasgow-coma-scale'
      preLoaderRoute: typeof CalcGlasgowComaScaleImport
      parentRoute: typeof rootRoute
    }
    '/calc/metabolic-acidosis': {
      id: '/calc/metabolic-acidosis'
      path: '/calc/metabolic-acidosis'
      fullPath: '/calc/metabolic-acidosis'
      preLoaderRoute: typeof CalcMetabolicAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/metabolic-alkalosis': {
      id: '/calc/metabolic-alkalosis'
      path: '/calc/metabolic-alkalosis'
      fullPath: '/calc/metabolic-alkalosis'
      preLoaderRoute: typeof CalcMetabolicAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/oxygen-gradient': {
      id: '/calc/oxygen-gradient'
      path: '/calc/oxygen-gradient'
      fullPath: '/calc/oxygen-gradient'
      preLoaderRoute: typeof CalcOxygenGradientImport
      parentRoute: typeof rootRoute
    }
    '/calc/peak-flow-rate': {
      id: '/calc/peak-flow-rate'
      path: '/calc/peak-flow-rate'
      fullPath: '/calc/peak-flow-rate'
      preLoaderRoute: typeof CalcPeakFlowRateImport
      parentRoute: typeof rootRoute
    }
    '/conditions/$key': {
      id: '/conditions/$key'
      path: '/conditions/$key'
      fullPath: '/conditions/$key'
      preLoaderRoute: typeof ConditionsKeyImport
      parentRoute: typeof rootRoute
    }
    '/drugs/$key': {
      id: '/drugs/$key'
      path: '/drugs/$key'
      fullPath: '/drugs/$key'
      preLoaderRoute: typeof DrugsKeyImport
      parentRoute: typeof rootRoute
    }
    '/calc/': {
      id: '/calc/'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcIndexImport
      parentRoute: typeof rootRoute
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/drugs/': {
      id: '/drugs/'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof DrugsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchLazyRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/anion-gap': typeof CalcAnionGapRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/corrected-sodium': typeof CalcCorrectedSodiumRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/calc/peak-flow-rate': typeof CalcPeakFlowRateRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$key': typeof DrugsKeyRoute
  '/calc': typeof CalcIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/drugs': typeof DrugsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchLazyRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/anion-gap': typeof CalcAnionGapRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/corrected-sodium': typeof CalcCorrectedSodiumRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/calc/peak-flow-rate': typeof CalcPeakFlowRateRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$key': typeof DrugsKeyRoute
  '/calc': typeof CalcIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/drugs': typeof DrugsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/search': typeof SearchLazyRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/anion-gap': typeof CalcAnionGapRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/corrected-sodium': typeof CalcCorrectedSodiumRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/calc/peak-flow-rate': typeof CalcPeakFlowRateRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$key': typeof DrugsKeyRoute
  '/calc/': typeof CalcIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/drugs/': typeof DrugsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/anion-gap'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/corrected-sodium'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/calc/peak-flow-rate'
    | '/conditions/$key'
    | '/drugs/$key'
    | '/calc'
    | '/conditions'
    | '/drugs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/anion-gap'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/corrected-sodium'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/calc/peak-flow-rate'
    | '/conditions/$key'
    | '/drugs/$key'
    | '/calc'
    | '/conditions'
    | '/drugs'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/anion-gap'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/corrected-sodium'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/calc/peak-flow-rate'
    | '/conditions/$key'
    | '/drugs/$key'
    | '/calc/'
    | '/conditions/'
    | '/drugs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchLazyRoute: typeof SearchLazyRoute
  CalcAcuteRespiratoryAcidosisRoute: typeof CalcAcuteRespiratoryAcidosisRoute
  CalcAcuteRespiratoryAlkalosisRoute: typeof CalcAcuteRespiratoryAlkalosisRoute
  CalcAnionGapRoute: typeof CalcAnionGapRoute
  CalcChronicRespiratoryAcidosisRoute: typeof CalcChronicRespiratoryAcidosisRoute
  CalcChronicRespiratoryAlkalosisRoute: typeof CalcChronicRespiratoryAlkalosisRoute
  CalcCorrectedSodiumRoute: typeof CalcCorrectedSodiumRoute
  CalcGlasgowComaScaleRoute: typeof CalcGlasgowComaScaleRoute
  CalcMetabolicAcidosisRoute: typeof CalcMetabolicAcidosisRoute
  CalcMetabolicAlkalosisRoute: typeof CalcMetabolicAlkalosisRoute
  CalcOxygenGradientRoute: typeof CalcOxygenGradientRoute
  CalcPeakFlowRateRoute: typeof CalcPeakFlowRateRoute
  ConditionsKeyRoute: typeof ConditionsKeyRoute
  DrugsKeyRoute: typeof DrugsKeyRoute
  CalcIndexRoute: typeof CalcIndexRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  DrugsIndexRoute: typeof DrugsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchLazyRoute: SearchLazyRoute,
  CalcAcuteRespiratoryAcidosisRoute: CalcAcuteRespiratoryAcidosisRoute,
  CalcAcuteRespiratoryAlkalosisRoute: CalcAcuteRespiratoryAlkalosisRoute,
  CalcAnionGapRoute: CalcAnionGapRoute,
  CalcChronicRespiratoryAcidosisRoute: CalcChronicRespiratoryAcidosisRoute,
  CalcChronicRespiratoryAlkalosisRoute: CalcChronicRespiratoryAlkalosisRoute,
  CalcCorrectedSodiumRoute: CalcCorrectedSodiumRoute,
  CalcGlasgowComaScaleRoute: CalcGlasgowComaScaleRoute,
  CalcMetabolicAcidosisRoute: CalcMetabolicAcidosisRoute,
  CalcMetabolicAlkalosisRoute: CalcMetabolicAlkalosisRoute,
  CalcOxygenGradientRoute: CalcOxygenGradientRoute,
  CalcPeakFlowRateRoute: CalcPeakFlowRateRoute,
  ConditionsKeyRoute: ConditionsKeyRoute,
  DrugsKeyRoute: DrugsKeyRoute,
  CalcIndexRoute: CalcIndexRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  DrugsIndexRoute: DrugsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/search",
        "/calc/acute-respiratory-acidosis",
        "/calc/acute-respiratory-alkalosis",
        "/calc/anion-gap",
        "/calc/chronic-respiratory-acidosis",
        "/calc/chronic-respiratory-alkalosis",
        "/calc/corrected-sodium",
        "/calc/glasgow-coma-scale",
        "/calc/metabolic-acidosis",
        "/calc/metabolic-alkalosis",
        "/calc/oxygen-gradient",
        "/calc/peak-flow-rate",
        "/conditions/$key",
        "/drugs/$key",
        "/calc/",
        "/conditions/",
        "/drugs/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/search": {
      "filePath": "search.lazy.tsx"
    },
    "/calc/acute-respiratory-acidosis": {
      "filePath": "calc/acute-respiratory-acidosis.tsx"
    },
    "/calc/acute-respiratory-alkalosis": {
      "filePath": "calc/acute-respiratory-alkalosis.tsx"
    },
    "/calc/anion-gap": {
      "filePath": "calc/anion-gap.tsx"
    },
    "/calc/chronic-respiratory-acidosis": {
      "filePath": "calc/chronic-respiratory-acidosis.tsx"
    },
    "/calc/chronic-respiratory-alkalosis": {
      "filePath": "calc/chronic-respiratory-alkalosis.tsx"
    },
    "/calc/corrected-sodium": {
      "filePath": "calc/corrected-sodium.tsx"
    },
    "/calc/glasgow-coma-scale": {
      "filePath": "calc/glasgow-coma-scale.tsx"
    },
    "/calc/metabolic-acidosis": {
      "filePath": "calc/metabolic-acidosis.tsx"
    },
    "/calc/metabolic-alkalosis": {
      "filePath": "calc/metabolic-alkalosis.tsx"
    },
    "/calc/oxygen-gradient": {
      "filePath": "calc/oxygen-gradient.tsx"
    },
    "/calc/peak-flow-rate": {
      "filePath": "calc/peak-flow-rate.tsx"
    },
    "/conditions/$key": {
      "filePath": "conditions/$key.tsx"
    },
    "/drugs/$key": {
      "filePath": "drugs/$key.tsx"
    },
    "/calc/": {
      "filePath": "calc/index.tsx"
    },
    "/conditions/": {
      "filePath": "conditions/index.tsx"
    },
    "/drugs/": {
      "filePath": "drugs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
