/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CalcOxygenGradientImport } from './routes/calc/oxygen-gradient'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CalcOxygenGradientRoute = CalcOxygenGradientImport.update({
  id: '/calc/oxygen-gradient',
  path: '/calc/oxygen-gradient',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calc/oxygen-gradient': {
      id: '/calc/oxygen-gradient'
      path: '/calc/oxygen-gradient'
      fullPath: '/calc/oxygen-gradient'
      preLoaderRoute: typeof CalcOxygenGradientImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calc/oxygen-gradient'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calc/oxygen-gradient'
  id: '__root__' | '/' | '/calc/oxygen-gradient'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalcOxygenGradientRoute: typeof CalcOxygenGradientRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalcOxygenGradientRoute: CalcOxygenGradientRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calc/oxygen-gradient"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calc/oxygen-gradient": {
      "filePath": "calc/oxygen-gradient.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
