/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DrugsIndexImport } from './routes/drugs/index'
import { Route as ConditionsIndexImport } from './routes/conditions/index'
import { Route as CalcIndexImport } from './routes/calc/index'
import { Route as DrugsKeyImport } from './routes/drugs/$key'
import { Route as ConditionsKeyImport } from './routes/conditions/$key'
import { Route as CalcOxygenGradientImport } from './routes/calc/oxygen-gradient'
import { Route as CalcMetabolicAlkalosisImport } from './routes/calc/metabolic-alkalosis'
import { Route as CalcMetabolicAcidosisImport } from './routes/calc/metabolic-acidosis'
import { Route as CalcGlasgowComaScaleImport } from './routes/calc/glasgow-coma-scale'
import { Route as CalcChronicRespiratoryAlkalosisImport } from './routes/calc/chronic-respiratory-alkalosis'
import { Route as CalcChronicRespiratoryAcidosisImport } from './routes/calc/chronic-respiratory-acidosis'
import { Route as CalcAcuteRespiratoryAlkalosisImport } from './routes/calc/acute-respiratory-alkalosis'
import { Route as CalcAcuteRespiratoryAcidosisImport } from './routes/calc/acute-respiratory-acidosis'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DrugsIndexRoute = DrugsIndexImport.update({
  id: '/drugs/',
  path: '/drugs/',
  getParentRoute: () => rootRoute,
} as any)

const ConditionsIndexRoute = ConditionsIndexImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRoute,
} as any)

const CalcIndexRoute = CalcIndexImport.update({
  id: '/calc/',
  path: '/calc/',
  getParentRoute: () => rootRoute,
} as any)

const DrugsKeyRoute = DrugsKeyImport.update({
  id: '/drugs/$key',
  path: '/drugs/$key',
  getParentRoute: () => rootRoute,
} as any)

const ConditionsKeyRoute = ConditionsKeyImport.update({
  id: '/conditions/$key',
  path: '/conditions/$key',
  getParentRoute: () => rootRoute,
} as any)

const CalcOxygenGradientRoute = CalcOxygenGradientImport.update({
  id: '/calc/oxygen-gradient',
  path: '/calc/oxygen-gradient',
  getParentRoute: () => rootRoute,
} as any)

const CalcMetabolicAlkalosisRoute = CalcMetabolicAlkalosisImport.update({
  id: '/calc/metabolic-alkalosis',
  path: '/calc/metabolic-alkalosis',
  getParentRoute: () => rootRoute,
} as any)

const CalcMetabolicAcidosisRoute = CalcMetabolicAcidosisImport.update({
  id: '/calc/metabolic-acidosis',
  path: '/calc/metabolic-acidosis',
  getParentRoute: () => rootRoute,
} as any)

const CalcGlasgowComaScaleRoute = CalcGlasgowComaScaleImport.update({
  id: '/calc/glasgow-coma-scale',
  path: '/calc/glasgow-coma-scale',
  getParentRoute: () => rootRoute,
} as any)

const CalcChronicRespiratoryAlkalosisRoute =
  CalcChronicRespiratoryAlkalosisImport.update({
    id: '/calc/chronic-respiratory-alkalosis',
    path: '/calc/chronic-respiratory-alkalosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcChronicRespiratoryAcidosisRoute =
  CalcChronicRespiratoryAcidosisImport.update({
    id: '/calc/chronic-respiratory-acidosis',
    path: '/calc/chronic-respiratory-acidosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcAcuteRespiratoryAlkalosisRoute =
  CalcAcuteRespiratoryAlkalosisImport.update({
    id: '/calc/acute-respiratory-alkalosis',
    path: '/calc/acute-respiratory-alkalosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcAcuteRespiratoryAcidosisRoute =
  CalcAcuteRespiratoryAcidosisImport.update({
    id: '/calc/acute-respiratory-acidosis',
    path: '/calc/acute-respiratory-acidosis',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calc/acute-respiratory-acidosis': {
      id: '/calc/acute-respiratory-acidosis'
      path: '/calc/acute-respiratory-acidosis'
      fullPath: '/calc/acute-respiratory-acidosis'
      preLoaderRoute: typeof CalcAcuteRespiratoryAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/acute-respiratory-alkalosis': {
      id: '/calc/acute-respiratory-alkalosis'
      path: '/calc/acute-respiratory-alkalosis'
      fullPath: '/calc/acute-respiratory-alkalosis'
      preLoaderRoute: typeof CalcAcuteRespiratoryAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/chronic-respiratory-acidosis': {
      id: '/calc/chronic-respiratory-acidosis'
      path: '/calc/chronic-respiratory-acidosis'
      fullPath: '/calc/chronic-respiratory-acidosis'
      preLoaderRoute: typeof CalcChronicRespiratoryAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/chronic-respiratory-alkalosis': {
      id: '/calc/chronic-respiratory-alkalosis'
      path: '/calc/chronic-respiratory-alkalosis'
      fullPath: '/calc/chronic-respiratory-alkalosis'
      preLoaderRoute: typeof CalcChronicRespiratoryAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/glasgow-coma-scale': {
      id: '/calc/glasgow-coma-scale'
      path: '/calc/glasgow-coma-scale'
      fullPath: '/calc/glasgow-coma-scale'
      preLoaderRoute: typeof CalcGlasgowComaScaleImport
      parentRoute: typeof rootRoute
    }
    '/calc/metabolic-acidosis': {
      id: '/calc/metabolic-acidosis'
      path: '/calc/metabolic-acidosis'
      fullPath: '/calc/metabolic-acidosis'
      preLoaderRoute: typeof CalcMetabolicAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/metabolic-alkalosis': {
      id: '/calc/metabolic-alkalosis'
      path: '/calc/metabolic-alkalosis'
      fullPath: '/calc/metabolic-alkalosis'
      preLoaderRoute: typeof CalcMetabolicAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/oxygen-gradient': {
      id: '/calc/oxygen-gradient'
      path: '/calc/oxygen-gradient'
      fullPath: '/calc/oxygen-gradient'
      preLoaderRoute: typeof CalcOxygenGradientImport
      parentRoute: typeof rootRoute
    }
    '/conditions/$key': {
      id: '/conditions/$key'
      path: '/conditions/$key'
      fullPath: '/conditions/$key'
      preLoaderRoute: typeof ConditionsKeyImport
      parentRoute: typeof rootRoute
    }
    '/drugs/$key': {
      id: '/drugs/$key'
      path: '/drugs/$key'
      fullPath: '/drugs/$key'
      preLoaderRoute: typeof DrugsKeyImport
      parentRoute: typeof rootRoute
    }
    '/calc/': {
      id: '/calc/'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcIndexImport
      parentRoute: typeof rootRoute
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/drugs/': {
      id: '/drugs/'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof DrugsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$key': typeof DrugsKeyRoute
  '/calc': typeof CalcIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/drugs': typeof DrugsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$key': typeof DrugsKeyRoute
  '/calc': typeof CalcIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/drugs': typeof DrugsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$key': typeof DrugsKeyRoute
  '/calc/': typeof CalcIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/drugs/': typeof DrugsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/conditions/$key'
    | '/drugs/$key'
    | '/calc'
    | '/conditions'
    | '/drugs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/conditions/$key'
    | '/drugs/$key'
    | '/calc'
    | '/conditions'
    | '/drugs'
  id:
    | '__root__'
    | '/'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/conditions/$key'
    | '/drugs/$key'
    | '/calc/'
    | '/conditions/'
    | '/drugs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalcAcuteRespiratoryAcidosisRoute: typeof CalcAcuteRespiratoryAcidosisRoute
  CalcAcuteRespiratoryAlkalosisRoute: typeof CalcAcuteRespiratoryAlkalosisRoute
  CalcChronicRespiratoryAcidosisRoute: typeof CalcChronicRespiratoryAcidosisRoute
  CalcChronicRespiratoryAlkalosisRoute: typeof CalcChronicRespiratoryAlkalosisRoute
  CalcGlasgowComaScaleRoute: typeof CalcGlasgowComaScaleRoute
  CalcMetabolicAcidosisRoute: typeof CalcMetabolicAcidosisRoute
  CalcMetabolicAlkalosisRoute: typeof CalcMetabolicAlkalosisRoute
  CalcOxygenGradientRoute: typeof CalcOxygenGradientRoute
  ConditionsKeyRoute: typeof ConditionsKeyRoute
  DrugsKeyRoute: typeof DrugsKeyRoute
  CalcIndexRoute: typeof CalcIndexRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  DrugsIndexRoute: typeof DrugsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalcAcuteRespiratoryAcidosisRoute: CalcAcuteRespiratoryAcidosisRoute,
  CalcAcuteRespiratoryAlkalosisRoute: CalcAcuteRespiratoryAlkalosisRoute,
  CalcChronicRespiratoryAcidosisRoute: CalcChronicRespiratoryAcidosisRoute,
  CalcChronicRespiratoryAlkalosisRoute: CalcChronicRespiratoryAlkalosisRoute,
  CalcGlasgowComaScaleRoute: CalcGlasgowComaScaleRoute,
  CalcMetabolicAcidosisRoute: CalcMetabolicAcidosisRoute,
  CalcMetabolicAlkalosisRoute: CalcMetabolicAlkalosisRoute,
  CalcOxygenGradientRoute: CalcOxygenGradientRoute,
  ConditionsKeyRoute: ConditionsKeyRoute,
  DrugsKeyRoute: DrugsKeyRoute,
  CalcIndexRoute: CalcIndexRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  DrugsIndexRoute: DrugsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calc/acute-respiratory-acidosis",
        "/calc/acute-respiratory-alkalosis",
        "/calc/chronic-respiratory-acidosis",
        "/calc/chronic-respiratory-alkalosis",
        "/calc/glasgow-coma-scale",
        "/calc/metabolic-acidosis",
        "/calc/metabolic-alkalosis",
        "/calc/oxygen-gradient",
        "/conditions/$key",
        "/drugs/$key",
        "/calc/",
        "/conditions/",
        "/drugs/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calc/acute-respiratory-acidosis": {
      "filePath": "calc/acute-respiratory-acidosis.tsx"
    },
    "/calc/acute-respiratory-alkalosis": {
      "filePath": "calc/acute-respiratory-alkalosis.tsx"
    },
    "/calc/chronic-respiratory-acidosis": {
      "filePath": "calc/chronic-respiratory-acidosis.tsx"
    },
    "/calc/chronic-respiratory-alkalosis": {
      "filePath": "calc/chronic-respiratory-alkalosis.tsx"
    },
    "/calc/glasgow-coma-scale": {
      "filePath": "calc/glasgow-coma-scale.tsx"
    },
    "/calc/metabolic-acidosis": {
      "filePath": "calc/metabolic-acidosis.tsx"
    },
    "/calc/metabolic-alkalosis": {
      "filePath": "calc/metabolic-alkalosis.tsx"
    },
    "/calc/oxygen-gradient": {
      "filePath": "calc/oxygen-gradient.tsx"
    },
    "/conditions/$key": {
      "filePath": "conditions/$key.tsx"
    },
    "/drugs/$key": {
      "filePath": "drugs/$key.tsx"
    },
    "/calc/": {
      "filePath": "calc/index.tsx"
    },
    "/conditions/": {
      "filePath": "conditions/index.tsx"
    },
    "/drugs/": {
      "filePath": "drugs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
